### ISSUE TITLE
i can send msg but can`t see text conversation :(

### ISSUE THREAD

**Issue by kokomaster** [mgp25/WhatsAPI-Spanish#10]
hello mgp

i already registed my wa number and login successfully and i can add contacts

the problem i can send text msg but not showing in conversation dialog.

first i think it was from font so i write by english also not appear text msg

see screenshot
http://i.imgur.com/KMtV1rd.png

is there any solution? also not showing text responses

**Comment by kokomaster** [comment]
also not showing text responses

**Comment by manufuentescr** [comment]
use onGetMessage

WhatsAPI-Official is more updated

https://github.com/mgp25/WhatsAPI-Official

**Comment by kokomaster** [comment]
tankx

**Comment by mgp25** [comment]
Use WhatsAPI Official.

Regards
